# Makefile for Worksheet 1 - UFCFWK-15-2

# Compiler and assembler
NASM = nasm
NASMFLAGS = -f elf
GCC = gcc
CFLAGS = -m32 -c
LDFLAGS = -m32

# Executables
EXEC = task1 task1_2 task2_1 task2_2 task2_3

# Default

